name: publish

on: [ push ]

jobs:
  cd:
    name: "Deployment"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v1"
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SECRET_TOKEN }}

      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/ryanzeng1990/php:latest
          docker run ghcr.io/ryanzeng1990/php:latest
          docker push ghcr.io/ryanzeng1990/php:latest